"""
Django settings for mineral_licenses project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Загрузка переменных окружения из .env файла
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() in ('true', '1', 'yes')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    # In development, use insecure default
    # In production deployment, SECRET_KEY must be set via Replit Secrets
    SECRET_KEY = 'django-insecure-*kd=nc*+5frcmt#3ev&esny@u_wy6*6c(n8)+-5&nlqxg!hsja'
    if not DEBUG:
        raise ValueError("SECRET_KEY environment variable must be set when DEBUG=False (production mode)")

# ALLOWED_HOSTS configuration
ALLOWED_HOSTS_ENV = os.getenv('ALLOWED_HOSTS', '')
if ALLOWED_HOSTS_ENV:
    ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_ENV.split(',')]
else:
    if not DEBUG:
        raise ValueError("ALLOWED_HOSTS environment variable must be set when DEBUG=False (production mode)")
    ALLOWED_HOSTS = ['*']

# CSRF settings for Replit
CSRF_TRUSTED_ORIGINS = [
    'https://*.replit.dev',
    'https://*.repl.co',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'licenses',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mineral_licenses.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mineral_licenses.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

import dj_database_url

DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv('DATABASE_URL'),
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS settings
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

# Яндекс.Карты API ключ
# Получите свой API ключ на https://developer.tech.yandex.ru/
YANDEX_MAPS_API_KEY = os.getenv('YANDEX_MAPS_API_KEY', '')

# =============================================================================
# LDAP AUTHENTICATION (Мультидоменная поддержка)
# =============================================================================
# LDAP аутентификация по умолчанию ВЫКЛЮЧЕНА
# 
# Для активации установите переменную окружения: USE_LDAP=true
# 
# НОВАЯ ВОЗМОЖНОСТЬ: Поддержка нескольких доменов LDAP
# Пользователь может выбрать домен при входе или система автоматически определит домен
# 
# Подробная документация по настройке: см. LDAP_SETUP.md
# =============================================================================

USE_LDAP = os.getenv('USE_LDAP', 'false').lower() in ('true', '1', 'yes')

if USE_LDAP:
    # Настраиваем кастомный мультидоменный backend аутентификации
    AUTHENTICATION_BACKENDS = [
        'licenses.auth_backends.MultiDomainLDAPBackend',  # Мультидоменный LDAP backend
        'django.contrib.auth.backends.ModelBackend',  # Локальная БД Django (запасной вариант)
    ]
    
    # =============================================================================
    # КОНФИГУРАЦИЯ МУЛЬТИДОМЕННОГО LDAP
    # =============================================================================
    # 
    # Формат конфигурации:
    # LDAP_DOMAINS = {
    #     'domain_code': {  # Код домена (соответствует value в форме логина)
    #         'SERVER_URI': 'ldap://адрес-сервера:порт',
    #         'BIND_DN': 'CN=Служебная учетка,OU=...,DC=...',  # Опционально
    #         'BIND_PASSWORD': 'пароль_служебной_учетки',      # Опционально
    #         'USER_SEARCH_BASE': 'OU=Users,DC=domain,DC=local',
    #         'USER_SEARCH_FILTER': '(sAMAccountName=%(user)s)',  # Для Active Directory
    #     },
    # }
    # 
    # Примеры:
    # - Для Active Directory используйте: ldap://dc.domain.local:389 или ldaps://dc.domain.local:636 (SSL)
    # - Для OpenLDAP используйте: ldap://ldap.domain.local:389
    # 
    # USER_SEARCH_FILTER:
    # - Active Directory: (sAMAccountName=%(user)s)
    # - OpenLDAP: (uid=%(user)s)
    # 
    # BIND_DN и BIND_PASSWORD опциональны, но рекомендуются для корректной работы поиска пользователей
    # =============================================================================
    
    LDAP_DOMAINS = {
        # Домен 1 - пример конфигурации для Active Directory
        'domain1': {
            'SERVER_URI': os.getenv('LDAP_DOMAIN1_SERVER_URI', 'ldap://dc1.example.local:389'),
            'BIND_DN': os.getenv('LDAP_DOMAIN1_BIND_DN', ''),
            'BIND_PASSWORD': os.getenv('LDAP_DOMAIN1_BIND_PASSWORD', ''),
            'USER_SEARCH_BASE': os.getenv('LDAP_DOMAIN1_USER_SEARCH_BASE', 'OU=Users,DC=example,DC=local'),
            'USER_SEARCH_FILTER': os.getenv('LDAP_DOMAIN1_USER_SEARCH_FILTER', '(sAMAccountName=%(user)s)'),
        },
        
        # Домен 2 - добавьте свой второй домен
        'domain2': {
            'SERVER_URI': os.getenv('LDAP_DOMAIN2_SERVER_URI', 'ldap://dc2.company.local:389'),
            'BIND_DN': os.getenv('LDAP_DOMAIN2_BIND_DN', ''),
            'BIND_PASSWORD': os.getenv('LDAP_DOMAIN2_BIND_PASSWORD', ''),
            'USER_SEARCH_BASE': os.getenv('LDAP_DOMAIN2_USER_SEARCH_BASE', 'OU=Users,DC=company,DC=local'),
            'USER_SEARCH_FILTER': os.getenv('LDAP_DOMAIN2_USER_SEARCH_FILTER', '(sAMAccountName=%(user)s)'),
        },
        
        # Домен 3 - добавьте свой третий домен
        'domain3': {
            'SERVER_URI': os.getenv('LDAP_DOMAIN3_SERVER_URI', 'ldap://dc3.corp.local:389'),
            'BIND_DN': os.getenv('LDAP_DOMAIN3_BIND_DN', ''),
            'BIND_PASSWORD': os.getenv('LDAP_DOMAIN3_BIND_PASSWORD', ''),
            'USER_SEARCH_BASE': os.getenv('LDAP_DOMAIN3_USER_SEARCH_BASE', 'OU=Users,DC=corp,DC=local'),
            'USER_SEARCH_FILTER': os.getenv('LDAP_DOMAIN3_USER_SEARCH_FILTER', '(sAMAccountName=%(user)s)'),
        },
    }
    
    # Удаляем домены с пустым SERVER_URI (не настроенные)
    LDAP_DOMAINS = {k: v for k, v in LDAP_DOMAINS.items() if v.get('SERVER_URI')}
    
    print(f"✓ LDAP authentication enabled - {len(LDAP_DOMAINS)} domain(s) configured")
    
else:
    # LDAP выключен, используем только стандартную аутентификацию Django
    AUTHENTICATION_BACKENDS = [
        'django.contrib.auth.backends.ModelBackend',
    ]
    LDAP_DOMAINS = {}

# ЗАГЛУШКА: Внешняя база данных
# Замените на свои настройки при подключении к продакшн БД
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'your_database_name',
#         'USER': 'your_database_user',
#         'PASSWORD': 'your_database_password',
#         'HOST': 'your-database-host.com',
#         'PORT': '5432',
#     }
# }
