# Generated by Django 5.2.7 on 2025-10-16 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=100, unique=True, verbose_name='Номер лицензии')),
                ('license_type', models.CharField(max_length=200, verbose_name='Вид пользования недрами')),
                ('owner', models.CharField(max_length=300, verbose_name='Недропользователь')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('region', models.CharField(max_length=200, verbose_name='Регион')),
                ('area', models.CharField(blank=True, max_length=300, verbose_name='Участок недр')),
                ('issue_date', models.DateField(verbose_name='Дата выдачи')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('mineral_type', models.CharField(blank=True, max_length=200, verbose_name='Вид полезного ископаемого')),
                ('status', models.CharField(choices=[('active', 'Действующая'), ('expired', 'Истекла'), ('suspended', 'Приостановлена'), ('terminated', 'Прекращена')], default='active', max_length=50, verbose_name='Статус')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
            ],
            options={
                'verbose_name': 'Лицензия',
                'verbose_name_plural': 'Лицензии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название документа')),
                ('file', models.FileField(upload_to='license_documents/', verbose_name='Файл')),
                ('file_type', models.CharField(choices=[('license', 'Лицензия'), ('report', 'Отчет'), ('map', 'Карта'), ('other', 'Прочее')], default='other', max_length=50, verbose_name='Тип документа')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил пользователь')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='licenses.license', verbose_name='Лицензия')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
