# Generated by Django 5.2.7 on 2025-10-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='polygon_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Данные полигона (GeoJSON)'),
        ),
        migrations.AlterField(
            model_name='license',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='license',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота'),
        ),
    ]
